sudo : required
services:
  - docker

before_install:
  - docker build -t ganeshmani009/docker-react -f Dockerfile.dev
  
script:
  - docker run ganeshmani009/docker-react npm run test -- --coverage  