sudo : required
services:
  - docker

before_install:
  - docker build -t ganeshmani009/docker-react -f Dockerfile.dev .
  
script:
  - docker run ganeshmani009/docker-react npm run test -- --coverage  

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-068232061312"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_BS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_BS_SECRET_KEY"